### ISSUE TITLE
Android-Studio installieren

### ISSUE THREAD

**Issue by DustVoice** [Hansenberg-InfoLK/Schinkenbrot_Edu#5]
Installiert euch Android-Studio auf dem PC. Die Installationsdatei gibt es bei mir in 1EG, oder schreibt einen Kommentar unter das Issue, wohin ich in der Mittagspause kommen soll.

**Comment by DustVoice** [comment]
Falls ihr Probleme mit der Installation haben sollte, schaut auf meinem Blog vorbei (https://BrainFuq.wordpress.com) dort gibt es Lösungen. Ihr könnt dort auch in der Menüleiste Deutsch als Sprache auswählen.

**Comment by DustVoice** [comment]
@cakeboon, kannst du Julian bescheid sagen, er soll sich einen GitHub account erstellen und mir eine Nachricht schreiben, mit seinem Benutzernamen? THX

**Comment by DustVoice** [comment]
\cc @cakeboon

**Comment by cakeboon** [comment]
@DustVoice , Julian heißt BlackfangHand ich gebe ihm dann die SetUps

**Comment by DustVoice** [comment]
@cakeboon danke. Ich würde evtl. Bei ihm nacher nochmal vorbei schauen. Frag ihn mal wann er kann

**Comment by HolyBloodyMary** [comment]
@DustVoice wäre es möglich, dass du deine Festplatte morgen einfach in Info mitbringst, weil ich es in der Mittagspause verpeilt habe?

**Comment by DustVoice** [comment]
@HolyBloodyMary Klaro :)

**Comment by BlackfangHand** [comment]
@AlZiWi cool dann kann ich es nochmal beenden:D
