### ISSUE TITLE
Colors.xml analysieren

### ISSUE THREAD

**Issue by DustVoice** [Hansenberg-InfoLK/Schinkenbrot_Edu#8]
Analysiere kurz, wie die colors.xml in einer Android-App funktioniert.
_(Das geht auch ohne Android-Studio, also keine Ausrede ;) )_

Benutze dafür den Commit Nr. 75980b32d98c6207a7134a1b792c5726b5515f41
___
Schriebe außerdem einfach zur Übung einen _kurzen & knackigen_ Wiki-Artikel. 

_(Muss wirklich nicht lang sein, nur so, dass wenn es jemand noch einmal nachlesen möchte es auch versteht)_

**Comment by HolyBloodyMary** [comment]
Den Wiki-Artikel habe ich als eine neue Seite verfasst und "Colors" genannt.

**Comment by DustVoice** [comment]
@HolyBloodyMary Gute Arbeit! Habe dem Titel deines Wiki-Eintrags noch ein "(Issue #8)" hinzugefügt. Konntest du nicht wissen. Würde aber beim nächsten Mal dann die Syntax beibehalten. Also immer (Issue #IssueNumber) nach dem Titel hinzufügen.

**Comment by DustVoice** [comment]
@HolyBloodyMary Sehr schön. Schaue dir bitte trotzdem nochmal die Änderungen an. Das was ich verändert habe war **nicht** der Erwartungshorizont. Es soll einfach nur Klarheit schaffen. Die Änderungen siehst du, wenn du 

- auf den **Wiki-Artikel gehst**
- auf **Edit** gehst,
- dann auf **Page History**,
- dann die _Checkbox_ bei der **ersten** und **letzten Änderung** anklickst
- und dann auf **Compare** gehst.

Trotz alldem: **Nice Work**. Dafür kriegste sogar n Daumen nach Oben: :+1:

:grin:
